use pumpkin_nbt::{Nbt, deserializer::NbtReadHelperBedrock};
use std::{collections::HashMap, io::Cursor};
use syn::{Expr, ImplItem, Item, Lit, Member};

pub fn existing_definitions(source: &str) -> HashMap<String, Vec<u8>> {
    let mut definitions = HashMap::new();
    let file = syn::parse_file(source).expect("Generated item source must parse");
    for item in file.items {
        let Item::Impl(item) = item else {
            continue;
        };
        for item in item.items {
            let ImplItem::Const(item) = item else {
                continue;
            };
            let Expr::Struct(value) = item.expr else {
                continue;
            };
            let mut key = None;
            let mut bytes = None;
            for field in value.fields {
                let Member::Named(name) = field.member else {
                    continue;
                };
                let Expr::Lit(value) = field.expr else {
                    continue;
                };
                match value.lit {
                    Lit::Str(value) if name == "registry_key" => key = Some(value.value()),
                    Lit::ByteStr(value) if name == "definition_components" => {
                        bytes = Some(value.value())
                    }
                    _ => {}
                }
            }
            if let (Some(key), Some(bytes)) = (key, bytes) {
                definitions.insert(key, bytes);
            }
        }
    }
    definitions
}

pub fn definition_bytes(existing: Option<&[u8]>, definition: Nbt) -> Vec<u8> {
    // NBT compound ordering is immaterial; retain equivalent generated bytes to avoid churn.
    if let Some(bytes) = existing {
        let parsed = Nbt::read(&mut NbtReadHelperBedrock::new(&mut Cursor::new(bytes)));
        if parsed.as_ref().ok() == Some(&definition) {
            return bytes.to_vec();
        }
    }
    definition.write_bedrock().to_vec()
}

#[cfg(test)]
mod tests {
    use super::*;
    use pumpkin_nbt::NbtCompound;

    #[test]
    fn keeps_equivalent_bedrock_bytes_and_regenerates_changed_values() {
        let mut tag = NbtCompound::new();
        tag.put_int("one", 1);
        tag.put_int("two", 2);
        let definition = Nbt::new(String::new(), tag.clone());
        let one_first = b"\x0a\x00\x03\x03one\x02\x03\x03two\x04\x00";
        let two_first = b"\x0a\x00\x03\x03two\x04\x03\x03one\x02\x00";
        let fresh = definition.clone().write_bedrock();
        // Use a known equivalent order different from this compound's serializer order.
        let existing = if fresh.as_ref() == one_first {
            two_first.as_slice()
        } else {
            one_first.as_slice()
        };
        assert_ne!(fresh.as_ref(), existing);
        assert_eq!(definition_bytes(Some(existing), definition), existing);
        tag.put_int("one", 3);
        let changed = Nbt::new(String::new(), tag);
        let bytes = definition_bytes(Some(existing), changed.clone());
        assert_eq!(
            Nbt::read(&mut NbtReadHelperBedrock::new(&mut Cursor::new(bytes))).unwrap(),
            changed
        );
    }
}
